### ISSUE TITLE
Xkblayout module issues

### ISSUE THREAD

**Issue by thiagokokada** [enkore/i3pystatus#529]
After the introduction of PR #492, there are multiple issues in `xkblayout` modules that didn't occurred before:

- changing the layout externally (using setkbmap for example) doesn't update the layout in i3pystatus. To test, simply call something like:
`
    $ setxkbmap br
`
And look for the current keymap, it will still reflect the old one.
- changing the layout externally (again using setkbmap) doesn't allow the change of layout on click too. You need to restart i3pystatus, since it doesn't work anymore.

I tried to fix in PR #527, however now I get `Xkblayout: X11Error: Cannon open display ".0"` after running i3pystatus for some time, probably because X11 stops accepting requests from i3pystatus since it is calling it too much. And PR #527 only fixed the first issue, however the second one is still a problem.

@hcpl, any ideas (since you're the creator of xkbgroup too)?

**Comment by hcpl** [comment]
@m45t3r, sorry for dragging for so long.

The fix for xkbgroup has been rolled out. Both issues you pointed out should be solved by now if your PR #527 gets accepted again.

### Details

Fortunately, the "too much requests" is not an issue.

Due to a bug in `close_display()` method the `XCloseDisplay()` function never gets called, which leads to a file descriptor leakage. As a result, when the number of open fd reaches threshold, the `Xkblayout: X11Error: Cannon open display ".0"` pops up.

Unfortunately, the leakage has much more far-reaching implications, such as inability to open _any_ X window at all. Good thing this didn't affect you — or you had to reload i3bar every time you want to open a new window.

**Comment by m45t3r** [comment]
Trying fix #527 with xkbgroup 0.1.4.3. Can't say I won't have the X11Error bug yet (I am using for 30 minutes, no problem for now), however I still have the problem with, when calling setxbmap to set a keyboard layout, the i3pystatus' on click switch does not work anymore. I need to restart i3pystatus to get it woking.

Anyway, after reading xkbgroup code, I find it curious that simply calling `_xkb.open_display()` does not work. According to the code, `_xkb.open_display()` should call `self.close_display()`, however I need to explicitly call `_xkb.close_display()` or the fix does not work. Another bug maybe?

I am not really happy with the fix either way. Is there another way to do it without connecting and disconnecting to X11 every second? Is this actually a problem (I don't understand X11 too much to know if this would be a problem).

@hcpl, comments?
